name = "Modpack"
author = "Luna Simons <luna@bddvlpr.com>"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eacfcfe4fcd14113df21d1183ca8189640ad45d1a7378d1521f5a87fb7280ae"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
