name = "Modpack"
author = "Luna Simons <luna@bddvlpr.com>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "459ded70d09b4b9895927ed9a95ce67287f93a17b214a6ee8caad0706695ef8c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
